const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const INITIAL={participants:[],assignments:[],waitlist:[],rooms:[{id:'a',name:'Hall A',capacity:10,open:true},{id:'b',name:'Room B',capacity:8,open:true},{id:'c',name:'Room C',capacity:6,open:true},{id:'d',name:'Studio D',capacity:8,open:true}],workshops:[{id:'agents',name:'Agents lab',room:'a',time:'10:00–11:30'},{id:'design',name:'Product studio',room:'b',time:'10:00–11:30'},{id:'story',name:'Storytelling',room:'c',time:'10:00–11:30'}],history:[],revision:0,applied_revision:null};
let state;try{state=JSON.parse(localStorage.getItem('fieldwork-v1'))||structuredClone(INITIAL);}catch{state=structuredClone(INITIAL);}let view='overview',proposal=null;
const roomFor=w=>state.rooms.find(r=>r.id===w.room),label=id=>state.workshops.find(w=>w.id===id)?.name||'Waitlist';
function notice(text,error=false){$('notice').hidden=false;$('notice').textContent=text;$('notice').classList.toggle('error',error);}
function save(message,details={}){state.revision++;state.history.push({time:new Date().toISOString(),message,details});localStorage.setItem('fieldwork-v1',JSON.stringify(state));render();}
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);}
function parseCSV(text){let rows=[],row=[],value='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(c==='"'){if(quoted&&text[i+1]==='"'){value+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){row.push(value);value='';}else if((c==='\n'||c==='\r')&&!quoted){if(c==='\r'&&text[i+1]==='\n')i++;row.push(value);if(row.some(x=>x))rows.push(row);row=[];value='';}else value+=c;}if(quoted)throw Error('Unclosed quote in CSV.');row.push(value);if(row.some(x=>x))rows.push(row);const headers=rows.shift()||[];if(!['id,name,email,first_choice,second_choice','id,name,email,first_choice,second_choice,group_id'].includes(headers.join(',')))throw Error('CSV headers must be id,name,email,first_choice,second_choice, with optional group_id as the last column.');return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]||''])));}
function validateRoster(rows){if(!rows.length||rows.length>200)throw Error('Import between 1 and 200 people.');let ids=new Set(),emails=new Set();for(const p of rows){if(!p.id||!p.name||!p.email.includes('@')||p.email!==p.email.trim().toLowerCase()||p.name!==p.name.trim())throw Error('Clean missing, padded or mixed-case contact details before import.');if(ids.has(p.id)||emails.has(p.email))throw Error('Resolve duplicate IDs or emails before importing.');if(!state.workshops.some(w=>w.id===p.first_choice)||!state.workshops.some(w=>w.id===p.second_choice))throw Error('Workshop IDs must be agents, design or story.');ids.add(p.id);emails.add(p.email);}}
function validatePlan(plan){if(!plan||!Array.isArray(plan.assignments)||!Array.isArray(plan.waitlist))throw Error('Plan must contain assignments and waitlist arrays.');const seen=new Set(),counts={};for(const a of plan.assignments){const p=state.participants.find(p=>p.id===a.participant_id),w=state.workshops.find(w=>w.id===a.workshop_id);if(!p||!w)throw Error('A plan refers to an unknown participant or workshop.');if(seen.has(p.id))throw Error('A participant was assigned twice.');if(![p.first_choice,p.second_choice].includes(w.id))throw Error(p.name+' was assigned outside their preferences.');seen.add(p.id);counts[w.id]=(counts[w.id]||0)+1;}for(const id of plan.waitlist){if(typeof id!=='string'||seen.has(id)||!state.participants.some(p=>p.id===id))throw Error('Invalid or duplicated waiting-list participant.');seen.add(id);}if(seen.size!==state.participants.length)throw Error('Account for every participant exactly once.');for(const w of state.workshops){const r=roomFor(w);if((counts[w.id]||0)>(r.open?r.capacity:0))throw Error(w.name+' exceeds its available room capacity.');}const groups=new Map(),placement=new Map(plan.assignments.map(a=>[a.participant_id,a.workshop_id]));for(const p of state.participants){if(!p.group_id)continue;const destination=placement.get(p.id)||null;if(groups.has(p.group_id)&&groups.get(p.group_id)!==destination)throw Error('Keep group '+p.group_id+' together in one workshop or on the waitlist.');groups.set(p.group_id,destination);}return counts;}
function conflicts(){const counts=Object.fromEntries(state.workshops.map(w=>[w.id,state.assignments.filter(a=>a.workshop_id===w.id).length]));return state.workshops.filter(w=>counts[w.id]>(roomFor(w).open?roomFor(w).capacity:0)).map(w=>w.id);}
function board(){return '<div class="board">'+state.workshops.map(w=>{const room=roomFor(w),rows=state.assignments.filter(a=>a.workshop_id===w.id),capacity=room.open?room.capacity:0,bad=rows.length>capacity;return `<article class="workshop"><div class="workshop-head"><span class="status ${bad?'red':room.open?'':'amber'}">${bad?'Needs replanning':room.open?'Room ready':'Room closed'}</span><h3>${esc(w.name)}</h3><p>${esc(room.name)} · ${esc(w.time)}</p><div class="occupancy"><span>${rows.length} assigned</span><span>${capacity} seats</span></div><div class="bar"><i style="width:${Math.min(100,capacity?rows.length/capacity*100:100)}%"></i></div></div><div class="workshop-body">${rows.length?rows.map(a=>{const p=state.participants.find(p=>p.id===a.participant_id);return `<div class="person"><span>${esc(p.name)}</span><small>${p.group_id?esc(p.group_id)+' · ':''}${p.first_choice===w.id?'1st choice':'2nd choice'}</small></div>`}).join(''):'<div class="empty">Your allocation will appear here.</div>'}</div></article>`;}).join('')+'</div>';}
function importPanel(scope){return `<div class="panel"><h2>Bring the roster</h2><p>Import a cleaned CSV. The original showcase file includes duplicates and incomplete records for the agent to resolve.</p><label for="roster-file-${scope}">Import participant CSV</label><input type="file" id="roster-file-${scope}" data-input="roster" accept=".csv"><details><summary>Expected columns</summary><code>id,name,email,first_choice,second_choice[,group_id]</code><p>Optional group_id keeps a booking together. Workshop IDs: agents, design, story. Imports replace the roster and clear assignments.</p></details></div>`;}
function proposalPanel(){return `<div class="panel"><h2>Review an allocation</h2><p>Upload a plan. Every attendee, preference and capacity is checked before changes are accepted.</p><label for="plan-file">Import allocation JSON</label><input type="file" id="plan-file" accept=".json"><details><summary>Plan format</summary><code>{"assignments":[{"participant_id":"p01","workshop_id":"agents"}],"waitlist":["p02"]}</code></details><div id="proposal">${proposal?proposalHTML():''}</div></div>`;}
function proposalHTML(){const before=new Map(state.assignments.map(a=>[a.participant_id,a.workshop_id])),after=new Map(proposal.assignments.map(a=>[a.participant_id,a.workshop_id])),changes=state.participants.filter(p=>before.get(p.id)!==after.get(p.id));return `<div class="check-summary">Checks passed: all ${state.participants.length} attendees accounted for, no duplicate seats, preferences respected, room capacities respected.</div><p>${changes.length} changed assignments · ${proposal.waitlist.length} on waitlist</p>${changes.slice(0,12).map(p=>`<div class="diff"><span>${esc(p.name)}<br>${esc(label(before.get(p.id)))}</span><span>→</span><span>${esc(label(after.get(p.id)))}</span></div>`).join('')}<button class="primary" id="apply-plan">Apply verified allocation</button>`;}
function render(){
 $('event-caption').textContent=state.participants.length+' attendees · 3 workshops';
 const occupied=state.assignments.length,first=state.assignments.filter(a=>state.participants.find(p=>p.id===a.participant_id)?.first_choice===a.workshop_id).length;
 $('overview').innerHTML=`<div class="metrics"><div class="metric"><span>Imported attendees</span><strong>${state.participants.length}</strong><span>Unique registrations</span></div><div class="metric"><span>Assigned seats</span><strong>${occupied}</strong><span>${first} first preferences</span></div><div class="metric"><span>Waiting list</span><strong class="${state.waitlist.length?'warn':''}">${state.waitlist.length}</strong><span>Need another seat</span></div><div class="metric"><span>Capacity conflicts</span><strong class="${conflicts().length?'warn':''}">${conflicts().length}</strong><span>Checked against rooms</span></div></div><div class="section-head"><h2>Workshop board</h2><p>Preferences, capacity, accountability.</p></div>${board()}<div class="two-col">${importPanel('overview')}<div class="panel"><h2>Space to adapt</h2><p>Close a room to simulate a genuine operational change. Existing reservations stay visible until a new plan is accepted.</p>${state.rooms.map(r=>`<div class="room-line"><div><strong>${esc(r.name)}</strong><small>${r.capacity} seats · ${r.open?'Available':'Closed'}${r.id==='d'?' · Reserve room':''}</small></div>${r.id==='a'?`<button id="close-hall" ${!r.open?'disabled':''}>Close Hall A</button>`:r.id==='d'?`<button id="move-agents" ${state.workshops[0].room==='d'?'disabled':''}>Move Agents lab to Studio D</button>`:''}</div>`).join('')}</div></div>`;
 $('people').innerHTML=importPanel('people')+`<div class="panel"><div class="section-head"><h2>People</h2><p>${state.participants.length} imported records</p></div><table><thead><tr><th>ID</th><th>Participant</th><th>First choice</th><th>Second choice</th><th>Assignment</th></tr></thead><tbody>${state.participants.map(p=>`<tr><td>${esc(p.id)}</td><td class="person-name">${esc(p.name)}<br><span class="muted">${esc(p.email)}</span></td><td>${esc(label(p.first_choice))}</td><td>${esc(label(p.second_choice))}</td><td>${esc(label(state.assignments.find(a=>a.participant_id===p.id)?.workshop_id))}</td></tr>`).join('')}</tbody></table></div>`;
 $('allocation').innerHTML=board()+proposalPanel()+(state.waitlist.length?`<div class="panel"><h2>Waiting for a seat</h2>${state.waitlist.map(id=>`<div class="person">${esc(state.participants.find(p=>p.id===id)?.name)}</div>`).join('')}</div>`:'');
 $('activity').innerHTML=`<div class="panel"><h2>Every change has a record</h2>${state.history.slice().reverse().map(h=>`<div class="history-line"><time>${esc(new Date(h.time).toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}))}</time><div><h3>${esc(h.message)}</h3><p>${esc(JSON.stringify(h.details))}</p></div></div>`).join('')||'<p>No changes yet.</p>'}</div>`;
 // Only controls in the selected view are exposed to the browser connector.
 for(const section of document.querySelectorAll('main>section[id]'))section.hidden=section.id!==view;
 document.querySelectorAll('[data-input=roster]').forEach(input=>input.onchange=async()=>{try{const f=input.files[0];if(!f||f.size>120000)throw Error('Use a CSV under 120 KB.');const rows=parseCSV(await f.text());validateRoster(rows);state.participants=rows;state.assignments=[];state.waitlist=[];proposal=null;save('Imported participant roster',{participants:rows.length});notice('Imported '+rows.length+' unique participants.');}catch(e){notice(e.message,true);}});
 document.querySelectorAll('#plan-file').forEach(input=>input.onchange=async()=>{try{const f=input.files[0];if(!f||f.size>120000)throw Error('Use JSON under 120 KB.');proposal=JSON.parse(await f.text());validatePlan(proposal);render();notice('Allocation checked. Review the changes before applying.');}catch(e){proposal=null;render();notice(e.message,true);}});
 $('apply-plan')?.addEventListener('click',()=>{try{validatePlan(proposal);state.assignments=proposal.assignments;state.waitlist=proposal.waitlist;state.applied_revision=state.revision+1;proposal=null;save('Applied verified allocation',{assigned:state.assignments.length,waitlist:state.waitlist.length});notice('Allocation applied. Every participant and capacity was checked.');}catch(e){notice(e.message,true);}});
 $('close-hall')?.addEventListener('click',()=>{state.rooms[0].open=false;proposal=null;save('Hall A closed',{room:'a'});notice('Hall A is closed. Replan its affected reservations.');});
 $('move-agents')?.addEventListener('click',()=>{state.workshops[0].room='d';proposal=null;save('Moved Agents lab to Studio D',{capacity:8});notice('Agents lab now uses Studio D. Recheck its allocation against 8 seats.');});
 $('event-state').textContent=JSON.stringify({...state,conflicts:conflicts(),proposal_ready:!!proposal});
}
const titles={overview:['Event overview','One roster. Every seat accounted for.'],people:['The people','Every preference travels with its attendee.'],allocation:['Workshop allocation','Review the change before it becomes the plan.'],activity:['Change history','What changed, when, and why.']};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));$('view-title').textContent=titles[view][0];$('view-subtitle').textContent=titles[view][1];render();});
$('export').onclick=()=>download('event-operations.json',JSON.stringify({...state,conflicts:conflicts()},null,2),'application/json');
$('reset').onclick=()=>{state=structuredClone(INITIAL);proposal=null;save('Reset showcase');notice('Showcase data reset.');};render();
