"""Validate key design boundaries: contrast, English glyphs, and local references."""
import hashlib
import json
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import unquote, urlsplit
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parent
data = json.loads((ROOT / "tokens.json").read_text())

def luminance(color):
    rgb = [int(color[i:i+2], 16) / 255 for i in (1, 3, 5)]
    rgb = [v / 12.92 if v <= 0.04045 else ((v + 0.055) / 1.055) ** 2.4 for v in rgb]
    return sum(v*w for v, w in zip(rgb, (0.2126, 0.7152, 0.0722)))

def contrast(a, b):
    lower, upper = sorted((luminance(a), luminance(b)))
    return (upper + 0.05) / (lower + 0.05)

pairs = [(fg, bg, 4.5) for fg, bg in [
    ("text", "canvas"), ("text", "surface"), ("text", "surface-alt"),
    ("text-muted", "canvas"), ("text-muted", "surface"),
    ("on-accent", "accent"), ("on-accent", "accent-hover"),
    ("accent-text", "canvas"), ("accent-text", "surface"),
    ("on-accent-soft", "accent-soft"),
    ("success", "success-soft"), ("warning", "warning-soft"),
    ("danger", "danger-soft"), ("info", "info-soft"),
]] + [(fg, bg, 3) for fg, bg in [
    ("border-control", "surface"), ("border-control", "canvas"),
    ("focus", "surface"), ("focus", "canvas"),
]]
report = {"version": data["meta"]["version"], "scope": "Design assets only; not an application accessibility audit", "contrast": [], "fonts": [], "references": []}
for theme, values in data["themes"].items():
    for fg, bg, threshold in pairs:
        ratio = contrast(values[fg], values[bg])
        report["contrast"].append({"theme": theme, "foreground": fg, "background": bg, "ratio": round(ratio, 4), "minimum": threshold, "pass": ratio >= threshold})

sample = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,:;!?@&%()+-/’“”–—'
for path in sorted((ROOT / "fonts").glob("*.ttf")):
    font = TTFont(path)
    missing = [c for c in sample if ord(c) not in font.getBestCmap()]
    report["fonts"].append({"file": path.name, "missing": missing, "sha256": hashlib.sha256(path.read_bytes()).hexdigest(), "pass": not missing})

class References(HTMLParser):
    def __init__(self):
        super().__init__()
        self.refs = []
    def handle_starttag(self, tag, attrs):
        for attr, value in attrs:
            if attr in ("href", "src") and value:
                part = urlsplit(value)
                if not part.scheme and not part.netloc and part.path:
                    self.refs.append(unquote(part.path))

for path in (ROOT / "brand-guide.html", ROOT / "title-card.html"):
    parser = References()
    parser.feed(path.read_text())
    for ref in parser.refs:
        # validation.json is the file being generated by this script.
        exists = ref == "validation.json" or (path.parent / ref).exists()
        report["references"].append({"source": path.name, "target": ref, "pass": exists})

report["passed"] = all(item["pass"] for category in ("contrast", "fonts", "references") for item in report[category])
(ROOT / "validation.json").write_text(json.dumps(report, ensure_ascii=False, indent=2) + "\n")
print(json.dumps({"passed": report["passed"], "contrastPairs": len(report["contrast"]), "fonts": len(report["fonts"]), "references": len(report["references"])}))
raise SystemExit(0 if report["passed"] else 1)
