// Read-only views over persisted execution data. No seeded statistics.
export function createInsights({ $, api, esc, icon, leave, setRoute, getRoute, showView, header, renderSidebar, inspector, projectById, download }) {
  let report=null, filter='all', loading=false, last='', currentUsage=null;
  const status=value=>({needs_input:'Needs input',needs_review:'Needs review'}[value]||value);
  const number=value=>value==null?'Unknown':Number(value).toLocaleString('en-US');
  const money=value=>value==null?'Not recorded':value===0?'$0.00':value<0.0001?'< $0.0001':'$'+value.toFixed(value<0.01?4:2);
  const duration=value=>value==null?'Not recorded':value<1000?'< 1s':value<60000?Math.round(value/1000)+'s':Math.floor(value/60000)+'m '+Math.round(value%60000/1000)+'s';
  const estimate=cost=>cost.estimated_usd==null?'Not recorded':money(cost.estimated_usd)+(cost.cost_complete?'':' + unknown');
  const meta=(name,value)=>`<div><dt>${esc(name)}</dt><dd>${esc(value)}</dd></div>`;
  const operationList=o=>`<dl class="detail-meta">${meta('Skill executions',number(o.skill_calls))}${meta('Using an earlier version',number(o.reused_skill_calls))}${meta('Browser action attempts',number(o.browser_attempts))}${meta('Test cases executed',number(o.test_cases))}${meta('Test cases passed',number(o.test_cases_passed))}${meta('Versions installed',number(o.versions_installed))}</dl>`;
  function go(type,title){leave();setRoute({type,id:null,projectId:null});showView('library');header(title);renderSidebar();}
  async function open(){go('overview','Overview');$('library-view').innerHTML='<p class="view-description" role="status">Loading your work…</p>';await refresh(true);}
  function dailyActivity(){
    const days=Array.from({length:7},(_,i)=>{const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()-6+i);const end=new Date(date);end.setDate(end.getDate()+1);const tasks=report.runs.filter(r=>r.created_at*1000>=date&&r.created_at*1000<end);return {date,tasks,completed:tasks.filter(r=>r.status==='completed').length};});
    const max=Math.max(1,...days.map(d=>d.tasks.length));
    return `<div class="activity-week">${days.map(d=>`<div class="activity-day" title="${esc(d.date.toLocaleDateString('en-US'))}: ${d.completed} completed of ${d.tasks.length} tasks"><div class="activity-stack" aria-hidden="true">${Array.from({length:20},(_,i)=>`<i class="${i<Math.round(d.tasks.length/max*20)?i<Math.round(d.completed/max*20)?'complete':'other':''}"></i>`).join('')}</div><span>${d.date.toLocaleDateString('en-US',{weekday:'short'})}</span><strong>${d.tasks.length}</strong><span class="sr-only">tasks, ${d.completed} completed</span></div>`).join('')}</div>`;
  }
  function render(){
    if(!report||getRoute().type!=='overview')return;
    const expanded=$('library-view').querySelector('.overview-advanced')?.open;
    const s=report.summary,rows=report.runs.filter(r=>filter==='all'||(filter==='reuse'?r.operations.reused_skill_calls>0:filter==='stopped'?['failed','cancelled','interrupted'].includes(r.status):r.status==='completed'));
    $('library-view').innerHTML=`<div class="view-heading"><h1>Overview</h1><button class="secondary-button" data-action="new-task">${icon("plus")}New chat</button></div><p class="view-description">Pick up a task or review what changed.</p>
      <div class="overview-metrics overview-essential" aria-label="All-time activity">
        <div><span>Completed tasks</span><strong>${s.completed}<small> / ${s.tasks}</small></strong><p>${s.failed+s.stopped} stopped or failed${s.needs_attention?`, ${s.needs_attention} need attention`:''}${s.active?`, ${s.active} running`:''}</p></div>
        <div><span>Tasks using prior skills</span><strong>${s.reused_tasks}</strong><p>${s.reused_skill_calls} executions of earlier skills</p></div>
        <div><span>Model cost subtotal</span><strong class="cost-total">${s.estimated_usd==null?'Not recorded':money(s.estimated_usd)}</strong><p>${s.cost_complete_tasks} of ${s.tasks} tasks fully estimated</p></div>
      </div>
      <div class="history-toolbar"><h2>Task history</h2><label><span class="sr-only">Filter task history</span><select id="history-filter"><option value="all">All tasks</option><option value="completed">Completed</option><option value="stopped">Stopped or failed</option><option value="reuse">Used prior skills</option></select></label><button class="quiet-button" data-action="export-usage">Export</button></div>
      ${rows.length?`<div class="history-scroll"><table class="history-table"><thead><tr><th scope="col">Task</th><th scope="col">Status</th><th scope="col">Time</th><th scope="col">Est. model cost</th></tr></thead><tbody>${rows.map(r=>`<tr><td><button class="history-task" data-action="source-run" data-id="${esc(r.id)}">${esc(r.task)}</button><small>${esc(projectById(r.project_id)?.name||'Personal')} · ${new Date(r.created_at*1000).toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}${r.operations.reused_skill_calls?' · Prior skill used':''}</small></td><td><span class="task-state state-${['completed','running','queued'].includes(r.status)?r.status:'stopped'}">${esc(status(r.status))}</span></td><td>${duration(r.duration_ms)}</td><td><button class="inline-link" data-action="usage" data-id="${esc(r.id)}">${estimate(r.cost)}</button></td></tr>`).join('')}</tbody></table></div>`:`<div class="empty-state"><h2>${s.tasks?'No tasks in this view.':'Your first task starts here.'}</h2><p>Run a task to see its result, usage and learned skills.</p><button class="secondary-button" data-action="sample">Try sample data</button></div>`}
      <details class="overview-advanced"><summary>Activity &amp; learning statistics</summary><p class="field-note">${number(s.model_calls)} model calls · ${number(s.tokens)} reported tokens</p>      <div class="overview-middle"><section><div class="list-caption"><span>Last 7 days</span><span>Local time</span></div>${dailyActivity()}<p class="chart-key"><span class="chart-swatch"></span>Completed <span class="chart-swatch other"></span>Other tasks</p></section>
      <section class="learning-summary"><div class="list-caption"><span>Learning in practice</span><button class="inline-link" data-action="open-skills">View skills</button></div><dl>${meta('Active skills',s.active_skills)}${meta('Saved versions',s.versions)}${meta('Recorded test cases',s.test_cases)}${meta('Test cases that passed',s.test_cases_passed)}</dl><p class="field-note">Reuse means a skill version came from an earlier task. It does not prove a time saving.</p></section></div>
</details>
      <p class="field-note cost-footnote">Model cost uses the tariff recorded for each call, not a billing statement. Older tasks and missing usage remain unpriced. Local compute is not metered; no external MCP service is connected.</p>`;
    $ ('library-view').querySelector('.overview-advanced').open=Boolean(expanded);
    $('history-filter').value=filter;$('history-filter').onchange=e=>{filter=e.target.value;render();};
  }
  async function refresh(force=false){
    if(loading||getRoute().type!=='overview')return;loading=true;
    try{const next=await api('/api/analytics'),signature=JSON.stringify(next);report=next;if(force||signature!==last){render();last=signature;}}
    catch(e){if(force)$('library-view').innerHTML=`<div class="empty-state"><h2>Could not load history.</h2><p>${esc(e.message)}</p><button class="secondary-button" data-action="overview">Try again</button></div>`;}
    finally{loading=false;}
  }
  async function showUsage(id){
    const record=await api('/api/usage/'+encodeURIComponent(id));currentUsage=record;
    const c=record.cost, spend=record.spend_budget;
    inspector('Usage & cost',`<button class="text-button" data-action="source-run" data-id="${esc(id)}">Open this task</button><span class="sample-tag">${esc(status(record.status))}</span><h2>What this task used</h2><p class="description">${esc(record.task)}</p>
      <div class="usage-total"><span>Estimated model cost</span><strong>${estimate(c)}</strong><p>${c.known_cost_calls} of ${c.calls} calls priced${c.cost_complete?'':'. The total is incomplete'}.</p></div>
      <p class="field-note">${c.tracked?'Free-tier estimates use your confirmed project setting. Provider billing is not connected.':'This task predates detailed metering. Its price and per-call token split were not recorded.'}</p>
      ${c.paid_equivalent_usd!=null?`<details class="detail-section"><summary>What would paid usage cost?</summary><p>${money(c.paid_equivalent_usd)} for ${c.paid_equivalent_calls} calls with complete token data, at standard text rates. This is a comparison, not a charge.</p><a class="inline-link" href="https://ai.google.dev/gemini-api/docs/pricing" target="_blank" rel="noreferrer">Google pricing</a><p class="field-note">Rates checked ${esc(record.calls.find(r=>r.pricing)?.pricing.checked_at)}. Each call keeps its rate snapshot. Thinking tokens count as output; cached input is not counted twice.</p></details>`:''}
      ${spend?`<section class="detail-section"><h3>Financial admission</h3><dl class="detail-meta">${meta('Policy',spend.policy==='strict'?'Strict monetary admission':'Existing plan, no local USD guarantee')}${meta('Run limit',`$${esc(spend.max_usd)}`)}${meta('Reserved upper bound',spend.guaranteed?`$${esc(spend.reserved_upper_bound_usd)}`:'Unknown')}${meta('Blocked requests',number(spend.blocked?.length||0))}</dl><p class="field-note">Checked before inference. Free-tier admission depends on your confirmation that billing remains disabled. Provider billing is not connected.</p></section>`:''}
      <section class="detail-section"><h3>Model calls</h3><p class="field-note">Includes planning, writing skills and repairs. A failed response can still consume tokens.</p>${record.calls.map(r=>`<details class="usage-call"><summary><span>${r.call}. ${esc(r.purpose)}</span><span>${esc(r.status)} · ${duration(r.duration_ms)}</span></summary><p class="field-note">${esc(r.resolved_model||r.model)}</p><dl class="detail-meta">${meta('Input tokens',number(r.usage?.input))}${meta('Cached input (included)',number(r.usage?.cached_input))}${meta('Output tokens',number(r.usage?.output))}${meta('Thinking tokens',number(r.usage?.thinking))}${meta('Total tokens',number(r.usage?.total))}${meta('Estimated model cost',r.cost?.usd==null?'Unknown':money(r.cost.usd))}${meta('Paid-rate comparison',r.cost?.paid_equivalent_usd==null?'Unknown':money(r.cost.paid_equivalent_usd))}${meta('Configured tariff',r.pricing?.tier==='free_confirmed'?'Free, user confirmed':'Unknown')}</dl></details>`).join('')||'<p>No per-call records are available.</p>'}</section>
      <section class="detail-section"><h3>Recorded local operations</h3>${operationList(record.operations)}<p class="field-note">Browser attempts include failed actions. Test counts include repeated cases. Local browser and Python execution have no measured compute price. No external MCP service is connected.</p></section>
      <div class="detail-actions"><button class="quiet-button" data-action="usage" data-id="${esc(id)}">Refresh usage</button><button class="primary-button" data-action="source-run" data-id="${esc(id)}">Open chat</button><button class="secondary-button" data-action="export-task-usage">Export usage</button></div>`);
  }
  function guide(){
    go('guide','Quick guide');
    $('library-view').innerHTML=`<div class="view-heading"><h1>A task today.<br>A skill for next time.</h1></div><p class="view-description">Describe the result you need. Wisp can create a missing operation, test it, and keep it for later tasks. Follow the work and check the outcome.</p>
      <div class="guide-steps"><section><span class="guide-number">01</span><div><h2>Connect a model and add your inputs</h2><p>Open Personal workspace → Settings. Continue with ChatGPT, choose a model and select Activate model, or use Gemini configured in your local settings. Check Runtime &amp; limits before starting.</p><p>Attach source files with the + beside your message. State the outcome and the rules that matter. Text attachments up to 120 KB can be read; larger or binary files can be transferred but their contents are not interpreted. Limits are 10 MB per file and 20 MB per task.</p><p class="field-note">Tasks, readable attachments and relevant application content are sent to the selected model provider.</p><button class="secondary-button" data-action="sample">Try an example</button></div></section>
      <section><span class="guide-number">02</span><div><h2>Try a complete application task</h2><p>Open Computer → Open event operations. Review the prepared task and CSV, keep Use browser enabled, then send. If Fieldwork is already connected, choose Start a task. The agent cleans registrations, allocates seats and exports a report in this local event app.</p><p>After it completes, Computer → Prepare room change starts a new chat with a revised roster. Keep the browser connected so its current bookings remain available.</p><p class="field-note">The event and attendees are synthetic. Model calls, tests, application changes and exports really execute. A fresh attempt may fail or reuse skills already in your registry.</p><button class="secondary-button" data-action="computer">Open Computer</button></div></section>
      <section><span class="guide-number">03</span><div><h2>Follow the steps and check the result</h2><p>Expand task steps to see actions and tests. View evidence opens execution details; View result shows the output and downloadable files. One task runs at a time. Stop task prevents further steps after the current operation and does not undo earlier changes.</p><p>On an external website, review changes with Allow this step or Decline. If a task ends as Needs review, inspect the application before choosing I checked the result. Human confirmation is recorded separately from an automated check.</p><p class="field-note">Browser control uses a separate Chrome session and one allowed origin. Redirects and WebSockets are blocked, so some login flows are unsupported.</p></div></section>
      <section><span class="guide-number">04</span><div><h2>Reuse a skill or improve it</h2><p>In Library → Skills, inspect each operation's contract, permissions, code and versions. New chat clears conversation history; a new chat inside the same project can still use its saved skills. Attach fresh source data and any report needed as a baseline, then ask for the next outcome.</p><p>Choose Improve to describe incorrect behavior and the expected result. Test case accepts a concrete example. The new case must expose the old error, and a replacement must pass both new and previous tests. If no repair passes, the old version stays active. You can also deactivate a skill or select a previously tested version.</p><p class="field-note">Passing tests support those cases; they do not guarantee every future result. Execution details show which earlier skills were used and whether anything new was installed.</p><button class="secondary-button" data-action="open-skills">Explore skills</button></div></section>
      <section><span class="guide-number">05</span><div><h2>Save instructions or schedule work</h2><p>From a completed task, choose Save as workflow. Library → Saved workflows keeps its instructions for fresh inputs. Schedule uses the original task's inputs. Library → Schedules offers one-time or repeating runs and Pause.</p><p class="field-note">The local server must stay running and the computer awake. Schedules do not wake the machine. Application tasks need the same target connected and keep normal approval requirements. Dispatch failures pause the schedule.</p><button class="secondary-button" data-action="open-workflows">Saved workflows</button></div></section>
      <section><span class="guide-number">06</span><div><h2>Review usage and recover from a stop</h2><p>Overview shows outcomes and use of earlier skills. Open More options on a task for Usage &amp; cost, including failed attempts when usage is available. Estimates are not a bill. Runtime &amp; limits shows the separate financial admission policy. Strict mode blocks unpriced requests; ChatGPT plan mode has no local USD guarantee.</p><p>If a task stops, read its error and steps first. Supply missing inputs, restore the connection or wait for provider quota before retrying. The app does not automatically switch providers or use a paid API fallback.</p><button class="secondary-button" data-action="overview">View overview</button></div></section>
      <section><span class="guide-number">07</span><div><h2>Run saved actions with AI paused</h2><p>PATCH turns tested compute skills into actions in Library → Actions. Open one, review or import inputs, then choose Preview result. Download the result, or explicitly apply a supported preview to Fieldwork. Replacing its roster clears existing seat assignments.</p><p>When no task is running, turn on Blackout in the header. AI tasks, corrections and scheduled AI dispatches pause; saved actions still run locally with 0 AI calls. Resume AI for new instructions or learning, and review any paused schedules.</p><p class="field-note">Blackout does not disconnect the internet. Keep the server and Docker running. Zero calls excludes earlier learning and local compute costs.</p><button class="secondary-button" data-local="list">Open actions</button></div></section></div>
      <p class="field-note">Desktop control is experimental: macOS Accessibility permission and approval of each change are required, and live native interaction remains unverified. Team sharing and external MCP connections are not implemented.</p>`;
  }
  return {open,refresh,showUsage,guide,exportAll:()=>report&&download(report,'workspace-usage.json'),exportTask:()=>currentUsage&&download(currentUsage,`usage-${currentUsage.run_id.slice(0,8)}.json`)};
}
