// Application connections, file artifacts and durable local schedules.
export function createOperations({$,api,esc,icon,toast,inspector,leave,setRoute,showView,header,renderSidebar,getState,getRoute,newChat,updateComposer,getFiles,setFiles,getData,persist,sourceRun}) {
 let desktop={connected:false},status=null,schedules=[],tab='browser';
 const desktopState=()=>desktop;
 function approval(){const pending=desktop.pending;if(!pending)return '';return `<div class="approval-card"><h3>Review the desktop action</h3><p>${esc(pending.reason)}</p><p class="field-note">${esc(pending.operation.action)} · ${esc(pending.operation.value??pending.operation.ref??'')}</p><button class="primary-button" data-op="approve-desktop">Allow this step</button><button class="quiet-button" data-op="decline-desktop">Decline</button></div>`;}
 function nativeView(){return `<div class="connection-tabs"><button data-op="browser-tab">Web browser</button><button class="selected" data-op="desktop-tab">Desktop application</button></div><p class="view-description">Connect one macOS application. The agent reads its Accessibility controls and can click or fill them with your approval.</p>${desktop.connected?`<div class="project-context-row">${icon('layers')}<div><h3>${esc(desktop.title)}</h3><p>${esc(desktop.bundle_id)} · ${desktop.elements?.length||0} controls</p></div><button class="quiet-button" data-op="disconnect-desktop">Disconnect</button></div><div class="browser-controls"><button class="primary-button" data-op="desktop-task">Start a task here</button><button class="quiet-button" data-op="refresh-desktop">Refresh controls</button></div><div id="native-live">${nativeMap()}</div>`:`<div class="connection-setup"><h2>${status?.trusted?'Choose an application':'Allow macOS Accessibility'}</h2><p class="description">${status?.trusted?'The connection grants access to this application’s windows only.':'Enable Workspace Desktop Bridge (or the app running this server) in System Settings → Privacy & Security → Accessibility. The connector cannot grant this permission itself.'}</p>${status?.error?`<p class="run-error">${esc(status.error)}</p>`:''}<label for="native-app">Running application</label><select id="native-app">${(status?.applications||[]).filter(a=>!['com.apple.systempreferences','com.apple.SecurityAgent','com.apple.loginwindow','com.apple.keychainaccess'].includes(a.bundle_id)).map(a=>`<option value="${esc(a.bundle_id)}">${esc(a.name)}</option>`).join('')}</select><div class="detail-actions"><button class="primary-button" data-op="connect-desktop" ${!status?.trusted?'disabled':''}>Connect application</button><button class="quiet-button" data-op="reveal-desktop">Show connector in Finder</button><button class="quiet-button" data-op="check-desktop">Check permission again</button></div></div>`}<p class="field-note">macOS only. Supports inspect, click and text entry through Accessibility. Canvas controls, protected fields, system permission dialogs and screenshots are outside this connector.</p>`;}
 function nativeMap(){return `${approval()}<div class="native-observation"><h3>Application content</h3><pre>${esc(desktop.text||'No readable window content.')}</pre></div><details class="detail-section"><summary>Mapped controls</summary>${(desktop.elements||[]).map(e=>`<div class="mapped-element"><code>${esc(e.ref)}</code><span>${esc(e.role)} · ${esc(e.name||'(unnamed)')}</span></div>`).join('')}</details>`;}
 async function native(){tab='desktop';status=await api('/api/desktop/status');renderNative();}
 function renderNative(){leave();setRoute({type:'computer',id:null,projectId:null});showView('library');header('Computer');renderSidebar();$('library-view').innerHTML=`<div class="view-heading"><h1>Computer</h1></div>${nativeView()}`;}
 function artifactHTML(run){return (run.artifacts||[]).length?`<div class="artifact-list">${run.artifacts.map(f=>`<a class="artifact-download" href="/api/files/${esc(f.id)}" download>${icon('file')}<span>${esc(f.name)}<small>${Math.ceil(f.size/1024)} KB · ${f.source==='browser_download'?'Downloaded from application':'Created during task'}</small></span><span>Save</span></a>`).join('')}</div>`:'';}
 async function attach(file){if(file.size>10*1024*1024)throw Error('Keep each file under 10 MB.');const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));return api('/api/files/upload',{name:file.name,base64:btoa(binary)});}
 async function showcaseProject(){let project=getData().projects.find(p=>p.id==='event-operations');if(!project){project={id:'event-operations',name:'Event operations',instructions:'Keep source records intact. Verify workshop preferences, available capacity and any requested preservation of existing bookings.'};getData().projects.push(project);if(!await persist())throw Error('Save the showcase project before continuing.');}return project.id;}
 async function showcase(){const project=await showcaseProject();const source=await api('/api/showcase/source');newChat(project);const f=await attach(new File([source.content],source.name,{type:'text/csv'}));setFiles([f]);$('message').value=source.task;$('use-browser').checked=true;updateComposer();toast('The original roster is attached. Review the task, then send it.');}
 async function followup(){const project=await showcaseProject();const source=await api('/api/showcase/source');newChat(project);const f=await attach(new File([source.followup_source.content],source.followup_source.name,{type:'text/csv'}));setFiles([f]);$('message').value=source.followup;$('use-browser').checked=true;updateComposer();toast('A new chat will test reuse without the previous conversation.');}
 async function openSchedules(){leave();setRoute({type:'schedules',id:null,projectId:null});showView('library');header('Library');renderSidebar();const result=await api('/api/schedules');schedules=result.schedules;renderSchedules();}
 function renderSchedules(){$('library-view').innerHTML=`<div class="view-heading"><h1>Schedules</h1><button class="primary-button" data-op="new-schedule">${icon('plus')}Schedule a task</button></div><p class="view-description">Choose when a task runs and how often it repeats.</p><div class="schedule-runtime">${icon('clock')}<span>Keep the local server running and your Mac awake. App changes may need your approval.</span></div>${schedules.length?schedules.map(s=>{const last=s.history?.at(-1),run=getState().runs.find(r=>r.id===last?.run_id);return `<article class="schedule-row"><div><strong>${esc(s.title)}</strong><p>${s.enabled?'Next: '+esc(new Date(s.next_at*1000).toLocaleString()):'Paused or completed'} · ${s.interval_minutes?`Every ${s.interval_minutes===1440?'day':s.interval_minutes===10080?'week':s.interval_minutes+' min'}`:'Once'}</p>${last?`<p class="field-note">Last attempt: ${esc(run?.status||last.status)}${last.error?' · '+esc(last.error):''}</p>`:''}</div><div>${last?.run_id?`<button class="text-button" data-op="schedule-result" data-id="${esc(last.run_id)}">View task</button>`:''}<button class="quiet-button" data-op="toggle-schedule" data-id="${esc(s.id)}">${s.enabled?'Pause':'Resume'}</button></div></article>`;}).join(''):`<div class="empty-state">${icon('clock')}<h2>Work that comes back.</h2><p>Start with a task or schedule an existing saved workflow. Every execution gets its own chat, usage report and result.</p></div>`}`;}
 function scheduleForm(workflow=null){const original=getState().runs.find(r=>r.id===workflow?.sourceRun),mode=workflow?.mode||'data';const when=new Date(Date.now()+3600000),local=new Date(when-when.getTimezoneOffset()*60000).toISOString().slice(0,16);inspector('Schedule',`<h2>${workflow?'Schedule this workflow':'A task, at the right time'}</h2><form id="schedule-form"><label for="schedule-title">Name</label><input id="schedule-title" maxlength="120" required value="${esc(workflow?.title||'')}"><label for="schedule-task">Task</label><textarea id="schedule-task" maxlength="4000" required>${esc(workflow?.prompt||'')}</textarea><label for="schedule-when">First run · your local time</label><input id="schedule-when" type="datetime-local" required value="${local}"><label for="schedule-repeat">Repeat</label><select id="schedule-repeat"><option value="0">Once</option><option value="15">Every 15 minutes</option><option value="60">Hourly</option><option value="1440">Daily</option><option value="10080">Weekly</option></select><p class="field-note">${workflow?'Uses the original task’s attached inputs.':'For tasks with files, save a completed workflow first.'} ${mode!=='data'?'The same application must stay connected. Mutations outside the showcase require approval.':''}</p><button class="primary-button" type="submit">Create schedule</button></form>`);$('schedule-form').onsubmit=async e=>{e.preventDefault();try{let source=original;if(workflow&&!source)source=await api('/api/runs/'+workflow.sourceRun);const connection=(source?.permissions||[]).find(p=>p.startsWith(mode==='desktop'?'desktop:':'browser:'));await api('/api/schedules/create',{title:$('schedule-title').value,task:$('schedule-task').value,next_at:new Date($('schedule-when').value).getTime()/1000,interval_minutes:Number($('schedule-repeat').value),input:source?.input||{},project_id:workflow?.projectId||null,mode,connection:mode==='browser'?connection?.slice(8):connection});toast('Schedule saved.');await openSchedules();}catch(error){toast(error.message);}};}
 async function poll(){desktop=await api('/api/desktop/state');if(getRoute().type==='schedules'&&!$('inspector').dataset.kind){schedules=(await api('/api/schedules')).schedules;renderSchedules();}if($('native-live'))$('native-live').innerHTML=nativeMap();if($('inspector').dataset.kind==='Desktop'&&$('desktop-inspector'))$('desktop-inspector').innerHTML=nativeMap();}
 function showDesktop(){inspector('Desktop',`<h2>${esc(desktop.title||'Desktop application')}</h2><div id="desktop-inspector">${nativeMap()}</div>`);}
 let onBrowser=()=>{};
 document.addEventListener('click',async e=>{const b=e.target.closest('[data-op]');if(!b)return;try{switch(b.dataset.op){case 'browser-tab':tab='browser';onBrowser();break;case 'desktop-tab':case 'check-desktop':await native();break;case 'reveal-desktop':await api('/api/desktop/reveal',{});toast('Add Workspace Desktop Bridge to macOS Accessibility if it is not listed.');break;case 'connect-desktop':desktop=await api('/api/desktop/connect',{bundle_id:$('native-app').value});renderNative();updateComposer();break;case 'disconnect-desktop':desktop=await api('/api/desktop/disconnect',{});renderNative();updateComposer();break;case 'refresh-desktop':desktop=await api('/api/desktop/refresh',{});renderNative();break;case 'desktop-task':newChat();$('use-browser').checked=false;$('use-desktop').checked=true;updateComposer();$('message').focus();break;case 'approve-desktop':await api('/api/desktop/approve',{approved:true});break;case 'decline-desktop':await api('/api/desktop/approve',{approved:false});break;case 'new-schedule':scheduleForm();break;case 'toggle-schedule':await api('/api/schedules/update',{id:b.dataset.id,enabled:!schedules.find(s=>s.id===b.dataset.id)?.enabled});await openSchedules();break;case 'schedule-result':await sourceRun(b.dataset.id);break;case 'showcase-task':await showcase();break;case 'showcase-followup':await followup();break;case 'show-desktop':showDesktop();break;}}catch(error){toast(error.message);}});
 return {desktopState,approval,artifactHTML,attach,showcase,followup,openSchedules,scheduleForm,poll,showDesktop,tab:()=>tab,setBrowser:fn=>onBrowser=fn};
}
